// Code generated by goctl. DO NOT EDIT.
package types

type AdminCommonResp struct {
}

type Admin struct {
	ID        string `json:"_id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type AdminSearchReq struct {
	Page       int64  `json:"page,optional"`        //第几页
	PageSize   int64  `json:"page_size,optional"`   //每页多少条
	OrderField string `json:"order_field,optional"` //排序字段
	OrderParam string `json:"order_param,optional"` //排序方法
	StartTime  int64  `json:"start_time,optional"`  //开始时间
	EndTime    int64  `json:"end_time,optional"`    //结束时间
}

type AdminSearchResp struct {
	Total int64    `json:"total"` // 总数
	List  []*Admin `json:"list"`  // 数据
}

type AdminUpdateReq struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type AdminDeleteReq struct {
	Id string `json:"id" validate:"required"` //id
}

type AdminAddReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email""`
}

type AdminDetailReq struct {
	Id string `form:"id" validate:"required"` //id
}

type AdminDetailResp struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
